// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: meerkat_protocol.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Action int32

const (
	Action_ADD    Action = 0
	Action_DELETE Action = 1
	Action_UPDATE Action = 2
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "ADD",
		1: "DELETE",
		2: "UPDATE",
	}
	Action_value = map[string]int32{
		"ADD":    0,
		"DELETE": 1,
		"UPDATE": 2,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_meerkat_protocol_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_meerkat_protocol_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_meerkat_protocol_proto_rawDescGZIP(), []int{0}
}

type PoolJoinRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Node enterieng sneds a request to join
	// with its address port and and empty
	// list of nodes it knows
	// string hostname = 1;
	// int32 port = 2;
	Address    string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	ClientList []string `protobuf:"bytes,2,rep,name=client_list,json=clientList,proto3" json:"client_list,omitempty"`
}

func (x *PoolJoinRequest) Reset() {
	*x = PoolJoinRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meerkat_protocol_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoolJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolJoinRequest) ProtoMessage() {}

func (x *PoolJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meerkat_protocol_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolJoinRequest.ProtoReflect.Descriptor instead.
func (*PoolJoinRequest) Descriptor() ([]byte, []int) {
	return file_meerkat_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *PoolJoinRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PoolJoinRequest) GetClientList() []string {
	if x != nil {
		return x.ClientList
	}
	return nil
}

type FileData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action Action `protobuf:"varint,1,opt,name=action,proto3,enum=meerkat_protocol.Action" json:"action,omitempty"`
	Path   string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Data   []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *FileData) Reset() {
	*x = FileData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meerkat_protocol_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileData) ProtoMessage() {}

func (x *FileData) ProtoReflect() protoreflect.Message {
	mi := &file_meerkat_protocol_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileData.ProtoReflect.Descriptor instead.
func (*FileData) Descriptor() ([]byte, []int) {
	return file_meerkat_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *FileData) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ADD
}

func (x *FileData) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DirData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *DirData) Reset() {
	*x = DirData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meerkat_protocol_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DirData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirData) ProtoMessage() {}

func (x *DirData) ProtoReflect() protoreflect.Message {
	mi := &file_meerkat_protocol_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirData.ProtoReflect.Descriptor instead.
func (*DirData) Descriptor() ([]byte, []int) {
	return file_meerkat_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *DirData) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ClientList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientList []string `protobuf:"bytes,1,rep,name=client_list,json=clientList,proto3" json:"client_list,omitempty"`
}

func (x *ClientList) Reset() {
	*x = ClientList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meerkat_protocol_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientList) ProtoMessage() {}

func (x *ClientList) ProtoReflect() protoreflect.Message {
	mi := &file_meerkat_protocol_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientList.ProtoReflect.Descriptor instead.
func (*ClientList) Descriptor() ([]byte, []int) {
	return file_meerkat_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *ClientList) GetClientList() []string {
	if x != nil {
		return x.ClientList
	}
	return nil
}

type PoolJoinResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The recieving node responds with a list
	// of nodes known to it and synced up data
	// "string" associated with it
	// repeated string client_list = 1;
	//
	// Types that are assignable to Response:
	//
	//	*PoolJoinResponse_ClientList
	//	*PoolJoinResponse_FileData
	//	*PoolJoinResponse_DirData
	Response isPoolJoinResponse_Response `protobuf_oneof:"response"`
}

func (x *PoolJoinResponse) Reset() {
	*x = PoolJoinResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meerkat_protocol_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoolJoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolJoinResponse) ProtoMessage() {}

func (x *PoolJoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meerkat_protocol_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolJoinResponse.ProtoReflect.Descriptor instead.
func (*PoolJoinResponse) Descriptor() ([]byte, []int) {
	return file_meerkat_protocol_proto_rawDescGZIP(), []int{4}
}

func (m *PoolJoinResponse) GetResponse() isPoolJoinResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *PoolJoinResponse) GetClientList() *ClientList {
	if x, ok := x.GetResponse().(*PoolJoinResponse_ClientList); ok {
		return x.ClientList
	}
	return nil
}

func (x *PoolJoinResponse) GetFileData() *FileData {
	if x, ok := x.GetResponse().(*PoolJoinResponse_FileData); ok {
		return x.FileData
	}
	return nil
}

func (x *PoolJoinResponse) GetDirData() *DirData {
	if x, ok := x.GetResponse().(*PoolJoinResponse_DirData); ok {
		return x.DirData
	}
	return nil
}

type isPoolJoinResponse_Response interface {
	isPoolJoinResponse_Response()
}

type PoolJoinResponse_ClientList struct {
	ClientList *ClientList `protobuf:"bytes,1,opt,name=client_list,json=clientList,proto3,oneof"`
}

type PoolJoinResponse_FileData struct {
	FileData *FileData `protobuf:"bytes,2,opt,name=file_data,json=fileData,proto3,oneof"`
}

type PoolJoinResponse_DirData struct {
	DirData *DirData `protobuf:"bytes,3,opt,name=dir_data,json=dirData,proto3,oneof"`
}

func (*PoolJoinResponse_ClientList) isPoolJoinResponse_Response() {}

func (*PoolJoinResponse_FileData) isPoolJoinResponse_Response() {}

func (*PoolJoinResponse_DirData) isPoolJoinResponse_Response() {}

type HeartBeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Somewhat like rafts hartbeat,
	// just to inform clients about its
	// presence
	Ping bool `protobuf:"varint,1,opt,name=ping,proto3" json:"ping,omitempty"`
}

func (x *HeartBeatRequest) Reset() {
	*x = HeartBeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meerkat_protocol_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartBeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatRequest) ProtoMessage() {}

func (x *HeartBeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meerkat_protocol_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatRequest.ProtoReflect.Descriptor instead.
func (*HeartBeatRequest) Descriptor() ([]byte, []int) {
	return file_meerkat_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *HeartBeatRequest) GetPing() bool {
	if x != nil {
		return x.Ping
	}
	return false
}

type HeartBeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ping bool `protobuf:"varint,1,opt,name=ping,proto3" json:"ping,omitempty"`
}

func (x *HeartBeatResponse) Reset() {
	*x = HeartBeatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meerkat_protocol_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartBeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatResponse) ProtoMessage() {}

func (x *HeartBeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meerkat_protocol_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatResponse.ProtoReflect.Descriptor instead.
func (*HeartBeatResponse) Descriptor() ([]byte, []int) {
	return file_meerkat_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *HeartBeatResponse) GetPing() bool {
	if x != nil {
		return x.Ping
	}
	return false
}

type DataModRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A client will stream the changed files
	// to nodes it is connected to
	// similar to pool response
	//
	// Types that are assignable to Response:
	//
	//	*DataModRequest_FileData
	//	*DataModRequest_DirData
	Response isDataModRequest_Response `protobuf_oneof:"response"`
}

func (x *DataModRequest) Reset() {
	*x = DataModRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meerkat_protocol_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataModRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataModRequest) ProtoMessage() {}

func (x *DataModRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meerkat_protocol_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataModRequest.ProtoReflect.Descriptor instead.
func (*DataModRequest) Descriptor() ([]byte, []int) {
	return file_meerkat_protocol_proto_rawDescGZIP(), []int{7}
}

func (m *DataModRequest) GetResponse() isDataModRequest_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *DataModRequest) GetFileData() *FileData {
	if x, ok := x.GetResponse().(*DataModRequest_FileData); ok {
		return x.FileData
	}
	return nil
}

func (x *DataModRequest) GetDirData() *DirData {
	if x, ok := x.GetResponse().(*DataModRequest_DirData); ok {
		return x.DirData
	}
	return nil
}

type isDataModRequest_Response interface {
	isDataModRequest_Response()
}

type DataModRequest_FileData struct {
	FileData *FileData `protobuf:"bytes,1,opt,name=file_data,json=fileData,proto3,oneof"`
}

type DataModRequest_DirData struct {
	DirData *DirData `protobuf:"bytes,2,opt,name=dir_data,json=dirData,proto3,oneof"`
}

func (*DataModRequest_FileData) isDataModRequest_Response() {}

func (*DataModRequest_DirData) isDataModRequest_Response() {}

type DataModResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// empty response
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DataModResponse) Reset() {
	*x = DataModResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meerkat_protocol_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataModResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataModResponse) ProtoMessage() {}

func (x *DataModResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meerkat_protocol_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataModResponse.ProtoReflect.Descriptor instead.
func (*DataModResponse) Descriptor() ([]byte, []int) {
	return file_meerkat_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *DataModResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PoolHandshakesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The recieving node responds with a list
	// of nodes known to it and synced up data
	// "string" associated with it
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// int32 port = 2;
	ClientList []string `protobuf:"bytes,2,rep,name=client_list,json=clientList,proto3" json:"client_list,omitempty"`
}

func (x *PoolHandshakesRequest) Reset() {
	*x = PoolHandshakesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meerkat_protocol_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoolHandshakesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolHandshakesRequest) ProtoMessage() {}

func (x *PoolHandshakesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meerkat_protocol_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolHandshakesRequest.ProtoReflect.Descriptor instead.
func (*PoolHandshakesRequest) Descriptor() ([]byte, []int) {
	return file_meerkat_protocol_proto_rawDescGZIP(), []int{9}
}

func (x *PoolHandshakesRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PoolHandshakesRequest) GetClientList() []string {
	if x != nil {
		return x.ClientList
	}
	return nil
}

type PoolHandshakeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// response back to the node that it has
	// updated its client list with the new node
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *PoolHandshakeResponse) Reset() {
	*x = PoolHandshakeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meerkat_protocol_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoolHandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolHandshakeResponse) ProtoMessage() {}

func (x *PoolHandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meerkat_protocol_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolHandshakeResponse.ProtoReflect.Descriptor instead.
func (*PoolHandshakeResponse) Descriptor() ([]byte, []int) {
	return file_meerkat_protocol_proto_rawDescGZIP(), []int{10}
}

func (x *PoolHandshakeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PoolDisconnectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Node leaving sends a request to leave
	// with its address and port
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // int32 port = 2;
}

func (x *PoolDisconnectRequest) Reset() {
	*x = PoolDisconnectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meerkat_protocol_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoolDisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolDisconnectRequest) ProtoMessage() {}

func (x *PoolDisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meerkat_protocol_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolDisconnectRequest.ProtoReflect.Descriptor instead.
func (*PoolDisconnectRequest) Descriptor() ([]byte, []int) {
	return file_meerkat_protocol_proto_rawDescGZIP(), []int{11}
}

func (x *PoolDisconnectRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type PoolDisconnectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// empty response
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *PoolDisconnectResponse) Reset() {
	*x = PoolDisconnectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meerkat_protocol_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoolDisconnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolDisconnectResponse) ProtoMessage() {}

func (x *PoolDisconnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meerkat_protocol_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolDisconnectResponse.ProtoReflect.Descriptor instead.
func (*PoolDisconnectResponse) Descriptor() ([]byte, []int) {
	return file_meerkat_protocol_proto_rawDescGZIP(), []int{12}
}

func (x *PoolDisconnectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type EchoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meerkat_protocol_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meerkat_protocol_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_meerkat_protocol_proto_rawDescGZIP(), []int{13}
}

func (x *EchoRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EchoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meerkat_protocol_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meerkat_protocol_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_meerkat_protocol_proto_rawDescGZIP(), []int{14}
}

func (x *EchoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HelloRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meerkat_protocol_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meerkat_protocol_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_meerkat_protocol_proto_rawDescGZIP(), []int{15}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HelloResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meerkat_protocol_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meerkat_protocol_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_meerkat_protocol_proto_rawDescGZIP(), []int{16}
}

func (x *HelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_meerkat_protocol_proto protoreflect.FileDescriptor

var file_meerkat_protocol_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6d, 0x65, 0x65, 0x72, 0x6b, 0x61, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x6d, 0x65, 0x65, 0x72, 0x6b, 0x61,
	0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0x4c, 0x0a, 0x0f, 0x50, 0x6f,
	0x6f, 0x6c, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x64, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x30, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x6d, 0x65, 0x65, 0x72, 0x6b, 0x61, 0x74, 0x5f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x1d,
	0x0a, 0x07, 0x44, 0x69, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x2d, 0x0a,
	0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x22, 0xd2, 0x01, 0x0a,
	0x10, 0x50, 0x6f, 0x6f, 0x6c, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3f, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x65, 0x65, 0x72, 0x6b, 0x61, 0x74,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x39, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x65, 0x65, 0x72, 0x6b, 0x61, 0x74, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x48, 0x00, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x36, 0x0a,
	0x08, 0x64, 0x69, 0x72, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x6d, 0x65, 0x65, 0x72, 0x6b, 0x61, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x44, 0x69, 0x72, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x07, 0x64, 0x69,
	0x72, 0x44, 0x61, 0x74, 0x61, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x26, 0x0a, 0x10, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x22, 0x27, 0x0a, 0x11, 0x48, 0x65, 0x61,
	0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x70, 0x69,
	0x6e, 0x67, 0x22, 0x8f, 0x01, 0x0a, 0x0e, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x6f, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x65, 0x65, 0x72, 0x6b,
	0x61, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x46, 0x69, 0x6c, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x36, 0x0a, 0x08, 0x64, 0x69, 0x72, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6d, 0x65, 0x65, 0x72, 0x6b, 0x61, 0x74, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x44, 0x69, 0x72, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52,
	0x07, 0x64, 0x69, 0x72, 0x44, 0x61, 0x74, 0x61, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2b, 0x0a, 0x0f, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x6f, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x22, 0x52, 0x0a, 0x15, 0x50, 0x6f, 0x6f, 0x6c, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61,
	0x6b, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x31, 0x0a, 0x15, 0x50, 0x6f, 0x6f, 0x6c, 0x48, 0x61, 0x6e,
	0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x31, 0x0a, 0x15, 0x50, 0x6f, 0x6f, 0x6c,
	0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x32, 0x0a, 0x16, 0x50,
	0x6f, 0x6f, 0x6c, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22,
	0x27, 0x0a, 0x0b, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x28, 0x0a, 0x0c, 0x45, 0x63, 0x68, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x22, 0x0a, 0x0c, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x29, 0x0a, 0x0d, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2a, 0x29, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x07, 0x0a, 0x03, 0x41,
	0x44, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x01,
	0x12, 0x0a, 0x0a, 0x06, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x02, 0x32, 0xc1, 0x04, 0x0a,
	0x0c, 0x4d, 0x65, 0x65, 0x72, 0x6b, 0x61, 0x74, 0x47, 0x75, 0x69, 0x64, 0x65, 0x12, 0x4d, 0x0a,
	0x08, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x1e, 0x2e, 0x6d, 0x65, 0x65, 0x72,
	0x6b, 0x61, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x48, 0x65, 0x6c,
	0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6d, 0x65, 0x65, 0x72,
	0x6b, 0x61, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x48, 0x65, 0x6c,
	0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x08,
	0x45, 0x63, 0x68, 0x6f, 0x54, 0x65, 0x78, 0x74, 0x12, 0x1d, 0x2e, 0x6d, 0x65, 0x65, 0x72, 0x6b,
	0x61, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x45, 0x63, 0x68, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6d, 0x65, 0x65, 0x72, 0x6b, 0x61,
	0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x45, 0x63, 0x68, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5d, 0x0a, 0x10, 0x4a, 0x6f, 0x69,
	0x6e, 0x50, 0x6f, 0x6f, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x21, 0x2e,
	0x6d, 0x65, 0x65, 0x72, 0x6b, 0x61, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x50, 0x6f, 0x6f, 0x6c, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x22, 0x2e, 0x6d, 0x65, 0x65, 0x72, 0x6b, 0x61, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x6f, 0x6f, 0x6c, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x6b, 0x0a, 0x15, 0x48, 0x61, 0x6e, 0x64,
	0x73, 0x68, 0x61, 0x6b, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x12, 0x27, 0x2e, 0x6d, 0x65, 0x65, 0x72, 0x6b, 0x61, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x6f, 0x6f, 0x6c, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61,
	0x6b, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x6d, 0x65, 0x65,
	0x72, 0x6b, 0x61, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x6f,
	0x6f, 0x6c, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6d, 0x0a, 0x16, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x50, 0x6f, 0x6f, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12,
	0x27, 0x2e, 0x6d, 0x65, 0x65, 0x72, 0x6b, 0x61, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x50, 0x6f, 0x6f, 0x6c, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x6d, 0x65, 0x65, 0x72, 0x6b,
	0x61, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x6f, 0x6f, 0x6c,
	0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x0f, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x6f, 0x64, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x20, 0x2e, 0x6d, 0x65, 0x65, 0x72, 0x6b, 0x61,
	0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x4d,
	0x6f, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x6d, 0x65, 0x65, 0x72,
	0x6b, 0x61, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x44, 0x61, 0x74,
	0x61, 0x4d, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01,
	0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_meerkat_protocol_proto_rawDescOnce sync.Once
	file_meerkat_protocol_proto_rawDescData = file_meerkat_protocol_proto_rawDesc
)

func file_meerkat_protocol_proto_rawDescGZIP() []byte {
	file_meerkat_protocol_proto_rawDescOnce.Do(func() {
		file_meerkat_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(file_meerkat_protocol_proto_rawDescData)
	})
	return file_meerkat_protocol_proto_rawDescData
}

var file_meerkat_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_meerkat_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_meerkat_protocol_proto_goTypes = []interface{}{
	(Action)(0),                    // 0: meerkat_protocol.Action
	(*PoolJoinRequest)(nil),        // 1: meerkat_protocol.PoolJoinRequest
	(*FileData)(nil),               // 2: meerkat_protocol.FileData
	(*DirData)(nil),                // 3: meerkat_protocol.DirData
	(*ClientList)(nil),             // 4: meerkat_protocol.ClientList
	(*PoolJoinResponse)(nil),       // 5: meerkat_protocol.PoolJoinResponse
	(*HeartBeatRequest)(nil),       // 6: meerkat_protocol.HeartBeatRequest
	(*HeartBeatResponse)(nil),      // 7: meerkat_protocol.HeartBeatResponse
	(*DataModRequest)(nil),         // 8: meerkat_protocol.DataModRequest
	(*DataModResponse)(nil),        // 9: meerkat_protocol.DataModResponse
	(*PoolHandshakesRequest)(nil),  // 10: meerkat_protocol.PoolHandshakesRequest
	(*PoolHandshakeResponse)(nil),  // 11: meerkat_protocol.PoolHandshakeResponse
	(*PoolDisconnectRequest)(nil),  // 12: meerkat_protocol.PoolDisconnectRequest
	(*PoolDisconnectResponse)(nil), // 13: meerkat_protocol.PoolDisconnectResponse
	(*EchoRequest)(nil),            // 14: meerkat_protocol.EchoRequest
	(*EchoResponse)(nil),           // 15: meerkat_protocol.EchoResponse
	(*HelloRequest)(nil),           // 16: meerkat_protocol.HelloRequest
	(*HelloResponse)(nil),          // 17: meerkat_protocol.HelloResponse
}
var file_meerkat_protocol_proto_depIdxs = []int32{
	0,  // 0: meerkat_protocol.FileData.action:type_name -> meerkat_protocol.Action
	4,  // 1: meerkat_protocol.PoolJoinResponse.client_list:type_name -> meerkat_protocol.ClientList
	2,  // 2: meerkat_protocol.PoolJoinResponse.file_data:type_name -> meerkat_protocol.FileData
	3,  // 3: meerkat_protocol.PoolJoinResponse.dir_data:type_name -> meerkat_protocol.DirData
	2,  // 4: meerkat_protocol.DataModRequest.file_data:type_name -> meerkat_protocol.FileData
	3,  // 5: meerkat_protocol.DataModRequest.dir_data:type_name -> meerkat_protocol.DirData
	16, // 6: meerkat_protocol.MeerkatGuide.SayHello:input_type -> meerkat_protocol.HelloRequest
	14, // 7: meerkat_protocol.MeerkatGuide.EchoText:input_type -> meerkat_protocol.EchoRequest
	1,  // 8: meerkat_protocol.MeerkatGuide.JoinPoolProtocol:input_type -> meerkat_protocol.PoolJoinRequest
	10, // 9: meerkat_protocol.MeerkatGuide.HandshakePoolProtocol:input_type -> meerkat_protocol.PoolHandshakesRequest
	12, // 10: meerkat_protocol.MeerkatGuide.DisconnectPoolProtocol:input_type -> meerkat_protocol.PoolDisconnectRequest
	8,  // 11: meerkat_protocol.MeerkatGuide.DataModProtocol:input_type -> meerkat_protocol.DataModRequest
	17, // 12: meerkat_protocol.MeerkatGuide.SayHello:output_type -> meerkat_protocol.HelloResponse
	15, // 13: meerkat_protocol.MeerkatGuide.EchoText:output_type -> meerkat_protocol.EchoResponse
	5,  // 14: meerkat_protocol.MeerkatGuide.JoinPoolProtocol:output_type -> meerkat_protocol.PoolJoinResponse
	11, // 15: meerkat_protocol.MeerkatGuide.HandshakePoolProtocol:output_type -> meerkat_protocol.PoolHandshakeResponse
	13, // 16: meerkat_protocol.MeerkatGuide.DisconnectPoolProtocol:output_type -> meerkat_protocol.PoolDisconnectResponse
	9,  // 17: meerkat_protocol.MeerkatGuide.DataModProtocol:output_type -> meerkat_protocol.DataModResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_meerkat_protocol_proto_init() }
func file_meerkat_protocol_proto_init() {
	if File_meerkat_protocol_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_meerkat_protocol_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoolJoinRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meerkat_protocol_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meerkat_protocol_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DirData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meerkat_protocol_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meerkat_protocol_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoolJoinResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meerkat_protocol_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartBeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meerkat_protocol_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartBeatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meerkat_protocol_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataModRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meerkat_protocol_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataModResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meerkat_protocol_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoolHandshakesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meerkat_protocol_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoolHandshakeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meerkat_protocol_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoolDisconnectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meerkat_protocol_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoolDisconnectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meerkat_protocol_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meerkat_protocol_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meerkat_protocol_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meerkat_protocol_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_meerkat_protocol_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*PoolJoinResponse_ClientList)(nil),
		(*PoolJoinResponse_FileData)(nil),
		(*PoolJoinResponse_DirData)(nil),
	}
	file_meerkat_protocol_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*DataModRequest_FileData)(nil),
		(*DataModRequest_DirData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meerkat_protocol_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meerkat_protocol_proto_goTypes,
		DependencyIndexes: file_meerkat_protocol_proto_depIdxs,
		EnumInfos:         file_meerkat_protocol_proto_enumTypes,
		MessageInfos:      file_meerkat_protocol_proto_msgTypes,
	}.Build()
	File_meerkat_protocol_proto = out.File
	file_meerkat_protocol_proto_rawDesc = nil
	file_meerkat_protocol_proto_goTypes = nil
	file_meerkat_protocol_proto_depIdxs = nil
}
