// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: meerkat_protocol.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MeerkatGuide_SayHello_FullMethodName = "/meerkat_protocol.MeerkatGuide/SayHello"
)

// MeerkatGuideClient is the client API for MeerkatGuide service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MeerkatGuideClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type meerkatGuideClient struct {
	cc grpc.ClientConnInterface
}

func NewMeerkatGuideClient(cc grpc.ClientConnInterface) MeerkatGuideClient {
	return &meerkatGuideClient{cc}
}

func (c *meerkatGuideClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, MeerkatGuide_SayHello_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeerkatGuideServer is the server API for MeerkatGuide service.
// All implementations must embed UnimplementedMeerkatGuideServer
// for forward compatibility
type MeerkatGuideServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedMeerkatGuideServer()
}

// UnimplementedMeerkatGuideServer must be embedded to have forward compatible implementations.
type UnimplementedMeerkatGuideServer struct {
}

func (UnimplementedMeerkatGuideServer) SayHello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedMeerkatGuideServer) mustEmbedUnimplementedMeerkatGuideServer() {}

// UnsafeMeerkatGuideServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeerkatGuideServer will
// result in compilation errors.
type UnsafeMeerkatGuideServer interface {
	mustEmbedUnimplementedMeerkatGuideServer()
}

func RegisterMeerkatGuideServer(s grpc.ServiceRegistrar, srv MeerkatGuideServer) {
	s.RegisterService(&MeerkatGuide_ServiceDesc, srv)
}

func _MeerkatGuide_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeerkatGuideServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeerkatGuide_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeerkatGuideServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MeerkatGuide_ServiceDesc is the grpc.ServiceDesc for MeerkatGuide service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MeerkatGuide_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meerkat_protocol.MeerkatGuide",
	HandlerType: (*MeerkatGuideServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _MeerkatGuide_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "meerkat_protocol.proto",
}
