// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: meerkat_protocol.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PoolJoinRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Node enterieng sneds a request to join
	// with its address port and and empty
	// list of nodes it knows
	// string hostname = 1;
	// int32 port = 2;
	Address    string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	ClientList []string `protobuf:"bytes,2,rep,name=client_list,json=clientList,proto3" json:"client_list,omitempty"`
}

func (x *PoolJoinRequest) Reset() {
	*x = PoolJoinRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meerkat_protocol_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoolJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolJoinRequest) ProtoMessage() {}

func (x *PoolJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meerkat_protocol_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolJoinRequest.ProtoReflect.Descriptor instead.
func (*PoolJoinRequest) Descriptor() ([]byte, []int) {
	return file_meerkat_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *PoolJoinRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PoolJoinRequest) GetClientList() []string {
	if x != nil {
		return x.ClientList
	}
	return nil
}

type PoolJoinResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The recieving node responds with a list
	// of nodes known to it and synced up data
	// "string" associated with it
	ClientList []string `protobuf:"bytes,1,rep,name=client_list,json=clientList,proto3" json:"client_list,omitempty"`
	Data       string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PoolJoinResponse) Reset() {
	*x = PoolJoinResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meerkat_protocol_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoolJoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolJoinResponse) ProtoMessage() {}

func (x *PoolJoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meerkat_protocol_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolJoinResponse.ProtoReflect.Descriptor instead.
func (*PoolJoinResponse) Descriptor() ([]byte, []int) {
	return file_meerkat_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *PoolJoinResponse) GetClientList() []string {
	if x != nil {
		return x.ClientList
	}
	return nil
}

func (x *PoolJoinResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type PoolHandshakesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The recieving node responds with a list
	// of nodes known to it and synced up data
	// "string" associated with it
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// int32 port = 2;
	ClientList []string `protobuf:"bytes,2,rep,name=client_list,json=clientList,proto3" json:"client_list,omitempty"`
}

func (x *PoolHandshakesRequest) Reset() {
	*x = PoolHandshakesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meerkat_protocol_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoolHandshakesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolHandshakesRequest) ProtoMessage() {}

func (x *PoolHandshakesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meerkat_protocol_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolHandshakesRequest.ProtoReflect.Descriptor instead.
func (*PoolHandshakesRequest) Descriptor() ([]byte, []int) {
	return file_meerkat_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *PoolHandshakesRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PoolHandshakesRequest) GetClientList() []string {
	if x != nil {
		return x.ClientList
	}
	return nil
}

type PoolHandshakeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// response back to the node that it has
	// updated its client list with the new node
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *PoolHandshakeResponse) Reset() {
	*x = PoolHandshakeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meerkat_protocol_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoolHandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolHandshakeResponse) ProtoMessage() {}

func (x *PoolHandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meerkat_protocol_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolHandshakeResponse.ProtoReflect.Descriptor instead.
func (*PoolHandshakeResponse) Descriptor() ([]byte, []int) {
	return file_meerkat_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *PoolHandshakeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PoolDisconnectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Node leaving sends a request to leave
	// with its address and port
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // int32 port = 2;
}

func (x *PoolDisconnectRequest) Reset() {
	*x = PoolDisconnectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meerkat_protocol_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoolDisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolDisconnectRequest) ProtoMessage() {}

func (x *PoolDisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meerkat_protocol_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolDisconnectRequest.ProtoReflect.Descriptor instead.
func (*PoolDisconnectRequest) Descriptor() ([]byte, []int) {
	return file_meerkat_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *PoolDisconnectRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type PoolDisconnectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// empty response
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *PoolDisconnectResponse) Reset() {
	*x = PoolDisconnectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meerkat_protocol_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoolDisconnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolDisconnectResponse) ProtoMessage() {}

func (x *PoolDisconnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meerkat_protocol_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolDisconnectResponse.ProtoReflect.Descriptor instead.
func (*PoolDisconnectResponse) Descriptor() ([]byte, []int) {
	return file_meerkat_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *PoolDisconnectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type EchoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meerkat_protocol_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meerkat_protocol_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_meerkat_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *EchoRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EchoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meerkat_protocol_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meerkat_protocol_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_meerkat_protocol_proto_rawDescGZIP(), []int{7}
}

func (x *EchoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HelloRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meerkat_protocol_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meerkat_protocol_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_meerkat_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HelloResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meerkat_protocol_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meerkat_protocol_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_meerkat_protocol_proto_rawDescGZIP(), []int{9}
}

func (x *HelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_meerkat_protocol_proto protoreflect.FileDescriptor

var file_meerkat_protocol_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6d, 0x65, 0x65, 0x72, 0x6b, 0x61, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x6d, 0x65, 0x65, 0x72, 0x6b, 0x61,
	0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0x4c, 0x0a, 0x0f, 0x50, 0x6f,
	0x6f, 0x6c, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x47, 0x0a, 0x10, 0x50, 0x6f, 0x6f, 0x6c,
	0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x52, 0x0a, 0x15, 0x50, 0x6f, 0x6f, 0x6c, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61,
	0x6b, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x31, 0x0a, 0x15, 0x50, 0x6f, 0x6f, 0x6c, 0x48, 0x61, 0x6e,
	0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x31, 0x0a, 0x15, 0x50, 0x6f, 0x6f, 0x6c,
	0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x32, 0x0a, 0x16, 0x50,
	0x6f, 0x6f, 0x6c, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22,
	0x27, 0x0a, 0x0b, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x28, 0x0a, 0x0c, 0x45, 0x63, 0x68, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x22, 0x0a, 0x0c, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x29, 0x0a, 0x0d, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x32, 0xe3, 0x03, 0x0a, 0x0c, 0x4d, 0x65, 0x65, 0x72, 0x6b, 0x61, 0x74, 0x47, 0x75, 0x69,
	0x64, 0x65, 0x12, 0x4d, 0x0a, 0x08, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x1e,
	0x2e, 0x6d, 0x65, 0x65, 0x72, 0x6b, 0x61, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f,
	0x2e, 0x6d, 0x65, 0x65, 0x72, 0x6b, 0x61, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x4b, 0x0a, 0x08, 0x45, 0x63, 0x68, 0x6f, 0x54, 0x65, 0x78, 0x74, 0x12, 0x1d, 0x2e,
	0x6d, 0x65, 0x65, 0x72, 0x6b, 0x61, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6d,
	0x65, 0x65, 0x72, 0x6b, 0x61, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5b,
	0x0a, 0x10, 0x4a, 0x6f, 0x69, 0x6e, 0x50, 0x6f, 0x6f, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x12, 0x21, 0x2e, 0x6d, 0x65, 0x65, 0x72, 0x6b, 0x61, 0x74, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x6f, 0x6f, 0x6c, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6d, 0x65, 0x65, 0x72, 0x6b, 0x61, 0x74, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x6f, 0x6f, 0x6c, 0x4a, 0x6f, 0x69,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6b, 0x0a, 0x15, 0x48,
	0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x27, 0x2e, 0x6d, 0x65, 0x65, 0x72, 0x6b, 0x61, 0x74, 0x5f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x6f, 0x6f, 0x6c, 0x48, 0x61, 0x6e, 0x64,
	0x73, 0x68, 0x61, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e,
	0x6d, 0x65, 0x65, 0x72, 0x6b, 0x61, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x50, 0x6f, 0x6f, 0x6c, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6d, 0x0a, 0x16, 0x44, 0x69, 0x73, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x50, 0x6f, 0x6f, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x12, 0x27, 0x2e, 0x6d, 0x65, 0x65, 0x72, 0x6b, 0x61, 0x74, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x6f, 0x6f, 0x6c, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x6d, 0x65,
	0x65, 0x72, 0x6b, 0x61, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50,
	0x6f, 0x6f, 0x6c, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_meerkat_protocol_proto_rawDescOnce sync.Once
	file_meerkat_protocol_proto_rawDescData = file_meerkat_protocol_proto_rawDesc
)

func file_meerkat_protocol_proto_rawDescGZIP() []byte {
	file_meerkat_protocol_proto_rawDescOnce.Do(func() {
		file_meerkat_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(file_meerkat_protocol_proto_rawDescData)
	})
	return file_meerkat_protocol_proto_rawDescData
}

var file_meerkat_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_meerkat_protocol_proto_goTypes = []interface{}{
	(*PoolJoinRequest)(nil),        // 0: meerkat_protocol.PoolJoinRequest
	(*PoolJoinResponse)(nil),       // 1: meerkat_protocol.PoolJoinResponse
	(*PoolHandshakesRequest)(nil),  // 2: meerkat_protocol.PoolHandshakesRequest
	(*PoolHandshakeResponse)(nil),  // 3: meerkat_protocol.PoolHandshakeResponse
	(*PoolDisconnectRequest)(nil),  // 4: meerkat_protocol.PoolDisconnectRequest
	(*PoolDisconnectResponse)(nil), // 5: meerkat_protocol.PoolDisconnectResponse
	(*EchoRequest)(nil),            // 6: meerkat_protocol.EchoRequest
	(*EchoResponse)(nil),           // 7: meerkat_protocol.EchoResponse
	(*HelloRequest)(nil),           // 8: meerkat_protocol.HelloRequest
	(*HelloResponse)(nil),          // 9: meerkat_protocol.HelloResponse
}
var file_meerkat_protocol_proto_depIdxs = []int32{
	8, // 0: meerkat_protocol.MeerkatGuide.SayHello:input_type -> meerkat_protocol.HelloRequest
	6, // 1: meerkat_protocol.MeerkatGuide.EchoText:input_type -> meerkat_protocol.EchoRequest
	0, // 2: meerkat_protocol.MeerkatGuide.JoinPoolProtocol:input_type -> meerkat_protocol.PoolJoinRequest
	2, // 3: meerkat_protocol.MeerkatGuide.HandshakePoolProtocol:input_type -> meerkat_protocol.PoolHandshakesRequest
	4, // 4: meerkat_protocol.MeerkatGuide.DisconnectPoolProtocol:input_type -> meerkat_protocol.PoolDisconnectRequest
	9, // 5: meerkat_protocol.MeerkatGuide.SayHello:output_type -> meerkat_protocol.HelloResponse
	7, // 6: meerkat_protocol.MeerkatGuide.EchoText:output_type -> meerkat_protocol.EchoResponse
	1, // 7: meerkat_protocol.MeerkatGuide.JoinPoolProtocol:output_type -> meerkat_protocol.PoolJoinResponse
	3, // 8: meerkat_protocol.MeerkatGuide.HandshakePoolProtocol:output_type -> meerkat_protocol.PoolHandshakeResponse
	5, // 9: meerkat_protocol.MeerkatGuide.DisconnectPoolProtocol:output_type -> meerkat_protocol.PoolDisconnectResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_meerkat_protocol_proto_init() }
func file_meerkat_protocol_proto_init() {
	if File_meerkat_protocol_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_meerkat_protocol_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoolJoinRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meerkat_protocol_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoolJoinResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meerkat_protocol_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoolHandshakesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meerkat_protocol_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoolHandshakeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meerkat_protocol_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoolDisconnectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meerkat_protocol_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoolDisconnectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meerkat_protocol_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meerkat_protocol_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meerkat_protocol_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meerkat_protocol_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meerkat_protocol_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meerkat_protocol_proto_goTypes,
		DependencyIndexes: file_meerkat_protocol_proto_depIdxs,
		MessageInfos:      file_meerkat_protocol_proto_msgTypes,
	}.Build()
	File_meerkat_protocol_proto = out.File
	file_meerkat_protocol_proto_rawDesc = nil
	file_meerkat_protocol_proto_goTypes = nil
	file_meerkat_protocol_proto_depIdxs = nil
}
